services:
  php-fpm:
    build:
      context: ./
      dockerfile: "docker/configs/php/Dockerfile"
    environment:
      XDEBUG_CONFIG: "remote_host={{YOUR_IP_ADDRESS}}"
      PHP_IDE_CONFIG: "serverName=docker"
    volumes:
      - ./:/srv/link-loom
      - ./docker/configs/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - backend

  redis:
    image: redis:latest
    volumes:
      - ./docker/configs/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - backend
      - monitoring  # отдельная сеть для мониторинга

networks:
  backend:
  monitoring:
