services:
  php-fpm:
    build:
      context: ./
      dockerfile: "docker/configs/php/Dockerfile"
    environment:
      XDEBUG_CONFIG: "remote_host={{YOUR_IP_ADDRESS}}"
      PHP_IDE_CONFIG: "serverName=docker"
    volumes:
      - ./:/srv/link-loom
      - ./docker/configs/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

